[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.db-start]
script_runner = "@shell"
script = '''
docker-compose up -d
'''

[tasks.db-stop]
script_runner = "@shell"
script = '''
docker-compose down
'''

[tasks.db-sh]
script_runner = "@shell"
script = '''
docker exec -it sqlserver2017 sh
'''

[tasks.db-create]
script_runner = "@shell"
script = '''
docker exec -it sqlserver2017 /sql/init.sh
'''

[tasks.db-reset]
dependencies = ["db-stop", "db-start", "db-create"]

