USE [WTPV_CALEIA_TEST]
GO

/****** Object:  Trigger [dbo].[PS_ARTICULOS_CAJAS]    Script Date: 21/03/2023 19:03:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TRIGGER [dbo].[PS_ARTICULOS_CAJAS]
   ON  [dbo].[TP_ARTICULO]
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	INSERT INTO TP_ARTICULO_CAJA (CAJTPV,ARTICULO,COSTE)
	SELECT X.CAJTPV,I.ARTICULO,0
	FROM INSERTED I
	CROSS JOIN (SELECT DISTINCT CAJTPV FROM TP_ARTICULO_CAJA) X 
	
	INSERT INTO TP_PRECIOS (CAJTPV,TIPOTARIFA,ARTICULO,PRECIO,PORCENTAJE_COMBINADO,PRECIO_COMBINADO)
	SELECT AC.CAJTPV,TP.TIPOTARIFA,AC.ARTICULO,0,100,0
	FROM INSERTED I 
	INNER JOIN TP_ARTICULO_CAJA AC ON AC.ARTICULO=I.ARTICULO
	CROSS JOIN (SELECT DISTINCT TIPOTARIFA FROM TP_PRECIOS) TP
	
    
END

GO

ALTER TABLE [dbo].[TP_ARTICULO] ENABLE TRIGGER [PS_ARTICULOS_CAJAS]
GO



